<?php

namespace Database\Seeders;

use App\Models\Attraction;
use App\Models\Country;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class AttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attractions = [
            // Paris Attractions
            [
                'name' => 'Eiffel Tower',
                'description' => 'An iconic iron lattice tower and symbol of Paris, offering breathtaking views of the city.',
                'type' => 'landmark',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France',
                'latitude' => 48.8584,
                'longitude' => 2.2945,
                'opening_hours' => [
                    'monday' => '09:30-23:45',
                    'tuesday' => '09:30-23:45',
                    'wednesday' => '09:30-23:45',
                    'thursday' => '09:30-23:45',
                    'friday' => '09:30-23:45',
                    'saturday' => '09:30-23:45',
                    'sunday' => '09:30-23:45',
                ],
                'admission_fee' => 29.40,
                'currency_code' => 'EUR',
                'amenities' => ['elevator', 'restaurant', 'gift_shop', 'guided_tours'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Louvre Museum',
                'description' => 'The world\'s largest art museum and historic monument, home to the Mona Lisa.',
                'type' => 'museum',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => 'Rue de Rivoli, 75001 Paris, France',
                'latitude' => 48.8606,
                'longitude' => 2.3376,
                'opening_hours' => [
                    'monday' => 'closed',
                    'tuesday' => '09:00-18:00',
                    'wednesday' => '09:00-21:45',
                    'thursday' => '09:00-18:00',
                    'friday' => '09:00-21:45',
                    'saturday' => '09:00-18:00',
                    'sunday' => '09:00-18:00',
                ],
                'admission_fee' => 17.00,
                'currency_code' => 'EUR',
                'amenities' => ['audio_guide', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Notre-Dame Cathedral',
                'description' => 'A medieval Catholic cathedral, famous for its French Gothic architecture.',
                'type' => 'religious_site',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris, France',
                'latitude' => 48.8530,
                'longitude' => 2.3499,
                'opening_hours' => [
                    'monday' => '08:00-18:45',
                    'tuesday' => '08:00-18:45',
                    'wednesday' => '08:00-18:45',
                    'thursday' => '08:00-18:45',
                    'friday' => '08:00-18:45',
                    'saturday' => '08:00-18:45',
                    'sunday' => '08:00-18:45',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['guided_tours', 'gift_shop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Tokyo Attractions
            [
                'name' => 'Tokyo Skytree',
                'description' => 'A broadcasting tower and landmark of Tokyo, offering panoramic views from its observation decks.',
                'type' => 'landmark',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '1 Chome-1-2 Oshiage, Sumida City, Tokyo 131-0045, Japan',
                'latitude' => 35.7101,
                'longitude' => 139.8107,
                'opening_hours' => [
                    'monday' => '08:00-22:00',
                    'tuesday' => '08:00-22:00',
                    'wednesday' => '08:00-22:00',
                    'thursday' => '08:00-22:00',
                    'friday' => '08:00-22:00',
                    'saturday' => '08:00-22:00',
                    'sunday' => '08:00-22:00',
                ],
                'admission_fee' => 2100.00,
                'currency_code' => 'JPY',
                'amenities' => ['elevator', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Senso-ji Temple',
                'description' => 'Tokyo\'s oldest temple, a significant Buddhist temple in Asakusa.',
                'type' => 'religious_site',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '2 Chome-3-1 Asakusa, Taito City, Tokyo 111-0032, Japan',
                'latitude' => 35.7148,
                'longitude' => 139.7967,
                'opening_hours' => [
                    'monday' => '06:00-17:00',
                    'tuesday' => '06:00-17:00',
                    'wednesday' => '06:00-17:00',
                    'thursday' => '06:00-17:00',
                    'friday' => '06:00-17:00',
                    'saturday' => '06:00-17:00',
                    'sunday' => '06:00-17:00',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'JPY',
                'amenities' => ['gift_shop', 'prayer_hall'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Tokyo National Museum',
                'description' => 'Japan\'s oldest and largest museum, housing a comprehensive collection of Japanese art.',
                'type' => 'museum',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '13-9 Uenokoen, Taito City, Tokyo 110-8712, Japan',
                'latitude' => 35.7186,
                'longitude' => 139.7765,
                'opening_hours' => [
                    'monday' => 'closed',
                    'tuesday' => '09:30-17:00',
                    'wednesday' => '09:30-17:00',
                    'thursday' => '09:30-17:00',
                    'friday' => '09:30-17:00',
                    'saturday' => '09:30-17:00',
                    'sunday' => '09:30-17:00',
                ],
                'admission_fee' => 1000.00,
                'currency_code' => 'JPY',
                'amenities' => ['audio_guide', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // New York City Attractions
            [
                'name' => 'Statue of Liberty',
                'description' => 'A symbol of freedom and democracy, this iconic statue stands on Liberty Island.',
                'type' => 'landmark',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => 'Liberty Island, New York, NY 10004, USA',
                'latitude' => 40.6892,
                'longitude' => -74.0445,
                'opening_hours' => [
                    'monday' => '09:30-15:30',
                    'tuesday' => '09:30-15:30',
                    'wednesday' => '09:30-15:30',
                    'thursday' => '09:30-15:30',
                    'friday' => '09:30-15:30',
                    'saturday' => '09:30-15:30',
                    'sunday' => '09:30-15:30',
                ],
                'admission_fee' => 24.00,
                'currency_code' => 'USD',
                'amenities' => ['ferry_service', 'audio_guide', 'gift_shop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Central Park',
                'description' => 'An urban park in Manhattan, offering a peaceful escape from the bustling city.',
                'type' => 'park',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => 'New York, NY, USA',
                'latitude' => 40.7829,
                'longitude' => -73.9654,
                'opening_hours' => [
                    'monday' => '06:00-01:00',
                    'tuesday' => '06:00-01:00',
                    'wednesday' => '06:00-01:00',
                    'thursday' => '06:00-01:00',
                    'friday' => '06:00-01:00',
                    'saturday' => '06:00-01:00',
                    'sunday' => '06:00-01:00',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'USD',
                'amenities' => ['walking_trails', 'bike_rental', 'boat_rental', 'playground'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Metropolitan Museum of Art',
                'description' => 'One of the world\'s largest and finest art museums, housing over 2 million works.',
                'type' => 'museum',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => '1000 5th Ave, New York, NY 10028, USA',
                'latitude' => 40.7794,
                'longitude' => -73.9632,
                'opening_hours' => [
                    'monday' => 'closed',
                    'tuesday' => '10:00-17:00',
                    'wednesday' => '10:00-17:00',
                    'thursday' => '10:00-17:00',
                    'friday' => '10:00-21:00',
                    'saturday' => '10:00-17:00',
                    'sunday' => '10:00-17:00',
                ],
                'admission_fee' => 30.00,
                'currency_code' => 'USD',
                'amenities' => ['audio_guide', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // London Attractions
            [
                'name' => 'Big Ben',
                'description' => 'The iconic clock tower of the Palace of Westminster, a symbol of London.',
                'type' => 'landmark',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Westminster, London SW1A 0AA, UK',
                'latitude' => 51.4994,
                'longitude' => -0.1245,
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'GBP',
                'amenities' => ['viewing_area'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'British Museum',
                'description' => 'A world-famous museum of human history, art, and culture with over 8 million works.',
                'type' => 'museum',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Great Russell St, London WC1B 3DG, UK',
                'latitude' => 51.5194,
                'longitude' => -0.1270,
                'opening_hours' => [
                    'monday' => '10:00-17:00',
                    'tuesday' => '10:00-17:00',
                    'wednesday' => '10:00-17:00',
                    'thursday' => '10:00-17:00',
                    'friday' => '10:00-17:00',
                    'saturday' => '10:00-17:00',
                    'sunday' => '10:00-17:00',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'GBP',
                'amenities' => ['audio_guide', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Tower of London',
                'description' => 'A historic castle on the north bank of the River Thames, home to the Crown Jewels.',
                'type' => 'historic_site',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'London EC3N 4AB, UK',
                'latitude' => 51.5081,
                'longitude' => -0.0759,
                'opening_hours' => [
                    'monday' => '09:00-17:30',
                    'tuesday' => '09:00-17:30',
                    'wednesday' => '09:00-17:30',
                    'thursday' => '09:00-17:30',
                    'friday' => '09:00-17:30',
                    'saturday' => '09:00-17:30',
                    'sunday' => '09:00-17:30',
                ],
                'admission_fee' => 29.90,
                'currency_code' => 'GBP',
                'amenities' => ['guided_tours', 'gift_shop', 'restaurant'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Rome Attractions
            [
                'name' => 'Colosseum',
                'description' => 'An ancient amphitheater and one of the most recognizable landmarks of Rome.',
                'type' => 'historic_site',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Piazza del Colosseo, 1, 00184 Roma RM, Italy',
                'latitude' => 41.8902,
                'longitude' => 12.4922,
                'opening_hours' => [
                    'monday' => '08:30-16:30',
                    'tuesday' => '08:30-16:30',
                    'wednesday' => '08:30-16:30',
                    'thursday' => '08:30-16:30',
                    'friday' => '08:30-16:30',
                    'saturday' => '08:30-16:30',
                    'sunday' => '08:30-16:30',
                ],
                'admission_fee' => 16.00,
                'currency_code' => 'EUR',
                'amenities' => ['audio_guide', 'guided_tours', 'gift_shop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Vatican City',
                'description' => 'The smallest country in the world, home to St. Peter\'s Basilica and the Vatican Museums.',
                'type' => 'religious_site',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Vatican City',
                'latitude' => 41.9029,
                'longitude' => 12.4534,
                'opening_hours' => [
                    'monday' => '08:00-18:00',
                    'tuesday' => '08:00-18:00',
                    'wednesday' => '08:00-18:00',
                    'thursday' => '08:00-18:00',
                    'friday' => '08:00-18:00',
                    'saturday' => '08:00-18:00',
                    'sunday' => '08:00-18:00',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['guided_tours', 'gift_shop', 'restaurant'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Sydney Attractions
            [
                'name' => 'Sydney Opera House',
                'description' => 'A masterpiece of modern architecture and one of the most recognizable buildings in the world.',
                'type' => 'landmark',
                'destination_name' => 'Sydney',
                'country_code' => 'AU',
                'address' => 'Bennelong Point, Sydney NSW 2000, Australia',
                'latitude' => -33.8568,
                'longitude' => 151.2153,
                'opening_hours' => [
                    'monday' => '09:00-17:00',
                    'tuesday' => '09:00-17:00',
                    'wednesday' => '09:00-17:00',
                    'thursday' => '09:00-17:00',
                    'friday' => '09:00-17:00',
                    'saturday' => '09:00-17:00',
                    'sunday' => '09:00-17:00',
                ],
                'admission_fee' => 43.00,
                'currency_code' => 'AUD',
                'amenities' => ['guided_tours', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Sydney Harbour Bridge',
                'description' => 'An iconic steel arch bridge across Sydney Harbour, offering spectacular views.',
                'type' => 'landmark',
                'destination_name' => 'Sydney',
                'country_code' => 'AU',
                'address' => 'Sydney Harbour Bridge, Sydney NSW, Australia',
                'latitude' => -33.8523,
                'longitude' => 151.2108,
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'AUD',
                'amenities' => ['bridge_climb', 'viewing_area'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Dubai Attractions
            [
                'name' => 'Burj Khalifa',
                'description' => 'The world\'s tallest building, offering breathtaking views from its observation decks.',
                'type' => 'landmark',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => '1 Sheikh Mohammed bin Rashid Blvd, Dubai, UAE',
                'latitude' => 25.1972,
                'longitude' => 55.2744,
                'opening_hours' => [
                    'monday' => '08:30-22:00',
                    'tuesday' => '08:30-22:00',
                    'wednesday' => '08:30-22:00',
                    'thursday' => '08:30-22:00',
                    'friday' => '08:30-22:00',
                    'saturday' => '08:30-22:00',
                    'sunday' => '08:30-22:00',
                ],
                'admission_fee' => 149.00,
                'currency_code' => 'AED',
                'amenities' => ['elevator', 'restaurant', 'gift_shop', 'wheelchair_accessible'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Dubai Mall',
                'description' => 'One of the world\'s largest shopping malls with over 1,200 retail stores.',
                'type' => 'shopping',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Financial Center Rd, Downtown Dubai, Dubai, UAE',
                'latitude' => 25.1972,
                'longitude' => 55.2796,
                'opening_hours' => [
                    'monday' => '10:00-23:00',
                    'tuesday' => '10:00-23:00',
                    'wednesday' => '10:00-23:00',
                    'thursday' => '10:00-23:00',
                    'friday' => '10:00-23:00',
                    'saturday' => '10:00-23:00',
                    'sunday' => '10:00-23:00',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'AED',
                'amenities' => ['restaurants', 'entertainment', 'aquarium', 'ice_rink'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Barcelona Attractions
            [
                'name' => 'Sagrada Familia',
                'description' => 'An unfinished basilica designed by Antoni Gaudí, a masterpiece of Catalan Modernism.',
                'type' => 'religious_site',
                'destination_name' => 'Barcelona',
                'country_code' => 'ES',
                'address' => 'Carrer de Mallorca, 401, 08013 Barcelona, Spain',
                'latitude' => 41.4036,
                'longitude' => 2.1744,
                'opening_hours' => [
                    'monday' => '09:00-18:00',
                    'tuesday' => '09:00-18:00',
                    'wednesday' => '09:00-18:00',
                    'thursday' => '09:00-18:00',
                    'friday' => '09:00-18:00',
                    'saturday' => '09:00-18:00',
                    'sunday' => '09:00-18:00',
                ],
                'admission_fee' => 26.00,
                'currency_code' => 'EUR',
                'amenities' => ['audio_guide', 'guided_tours', 'gift_shop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Park Güell',
                'description' => 'A public park system designed by Antoni Gaudí, featuring colorful mosaics and unique architecture.',
                'type' => 'park',
                'destination_name' => 'Barcelona',
                'country_code' => 'ES',
                'address' => '08024 Barcelona, Spain',
                'latitude' => 41.4145,
                'longitude' => 2.1527,
                'opening_hours' => [
                    'monday' => '08:30-18:15',
                    'tuesday' => '08:30-18:15',
                    'wednesday' => '08:30-18:15',
                    'thursday' => '08:30-18:15',
                    'friday' => '08:30-18:15',
                    'saturday' => '08:30-18:15',
                    'sunday' => '08:30-18:15',
                ],
                'admission_fee' => 10.00,
                'currency_code' => 'EUR',
                'amenities' => ['walking_trails', 'gift_shop', 'restaurant'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Bangkok Attractions
            [
                'name' => 'Grand Palace',
                'description' => 'The official residence of the Kings of Siam, featuring stunning Thai architecture.',
                'type' => 'historic_site',
                'destination_name' => 'Bangkok',
                'country_code' => 'TH',
                'address' => 'Na Phra Lan Rd, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok 10200, Thailand',
                'latitude' => 13.7500,
                'longitude' => 100.4916,
                'opening_hours' => [
                    'monday' => '08:30-15:30',
                    'tuesday' => '08:30-15:30',
                    'wednesday' => '08:30-15:30',
                    'thursday' => '08:30-15:30',
                    'friday' => '08:30-15:30',
                    'saturday' => '08:30-15:30',
                    'sunday' => '08:30-15:30',
                ],
                'admission_fee' => 500.00,
                'currency_code' => 'THB',
                'amenities' => ['guided_tours', 'gift_shop', 'dress_code_required'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Wat Pho',
                'description' => 'A Buddhist temple complex famous for its giant reclining Buddha statue.',
                'type' => 'religious_site',
                'destination_name' => 'Bangkok',
                'country_code' => 'TH',
                'address' => '2 Sanam Chai Rd, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok 10200, Thailand',
                'latitude' => 13.7466,
                'longitude' => 100.4948,
                'opening_hours' => [
                    'monday' => '08:00-18:30',
                    'tuesday' => '08:00-18:30',
                    'wednesday' => '08:00-18:30',
                    'thursday' => '08:00-18:30',
                    'friday' => '08:00-18:30',
                    'saturday' => '08:00-18:30',
                    'sunday' => '08:00-18:30',
                ],
                'admission_fee' => 200.00,
                'currency_code' => 'THB',
                'amenities' => ['massage_school', 'gift_shop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Santorini Attractions
            [
                'name' => 'Oia Village',
                'description' => 'A picturesque village famous for its white-washed buildings and stunning sunset views.',
                'type' => 'village',
                'destination_name' => 'Santorini',
                'country_code' => 'GR',
                'address' => 'Oia, Santorini 847 02, Greece',
                'latitude' => 36.4619,
                'longitude' => 25.3753,
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['restaurants', 'shops', 'hotels', 'viewing_points'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Red Beach',
                'description' => 'A unique beach with red volcanic sand and dramatic cliffs, one of Santorini\'s most famous beaches.',
                'type' => 'beach',
                'destination_name' => 'Santorini',
                'country_code' => 'GR',
                'address' => 'Red Beach, Santorini, Greece',
                'latitude' => 36.3500,
                'longitude' => 25.3833,
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['swimming', 'snorkeling', 'beach_access'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
        ];

        foreach ($attractions as $attractionData) {
            $country = Country::where('iso_code', $attractionData['country_code'])->first();
            $destination = Destination::where('name', $attractionData['destination_name'])->first();
            
            if ($country && $destination) {
                // Remove lookup fields that are not actual table columns
                $insertData = $attractionData;
                unset($insertData['destination_name'], $insertData['country_code']);
                
                Attraction::updateOrCreate(
                    [
                        'name' => $attractionData['name'],
                        'destination_id' => $destination->id,
                    ],
                    array_merge($insertData, [
                        'country_id' => $country->id,
                        'destination_id' => $destination->id,
                    ])
                );
            }
        }
    }
}


