<?php

namespace Database\Seeders;

use App\Models\Attraction;
use App\Models\Country;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class AttractionHotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hotelAttractions = [
            // Paris Hotels
            [
                'name' => 'Hotel Ritz Paris',
                'description' => 'A legendary luxury hotel in the heart of Paris, offering world-class service and elegant accommodations.',
                'type' => 'hotel',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '15 Place Vendôme, 75001 Paris, France',
                'latitude' => 48.8676,
                'longitude' => 2.3307,
                'phone' => '+33 1 43 16 30 30',
                'email' => 'reservations@ritzparis.com',
                'website' => 'https://www.ritzparis.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Le Meurice',
                'description' => 'A prestigious palace hotel overlooking the Tuileries Garden, known for its exceptional service and luxurious accommodations.',
                'type' => 'hotel',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '228 Rue de Rivoli, 75001 Paris, France',
                'latitude' => 48.8656,
                'longitude' => 2.3286,
                'phone' => '+33 1 44 58 10 10',
                'email' => 'reservations@lemeurice.com',
                'website' => 'https://www.lemeurice.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Hotel Plaza Athénée',
                'description' => 'An iconic luxury hotel on Avenue Montaigne, famous for its elegant rooms and world-class dining.',
                'type' => 'hotel',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '25 Avenue Montaigne, 75008 Paris, France',
                'latitude' => 48.8661,
                'longitude' => 2.3044,
                'phone' => '+33 1 53 67 66 65',
                'email' => 'reservations@plaza-athenee-paris.com',
                'website' => 'https://www.plaza-athenee-paris.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],

            // London Hotels
            [
                'name' => 'The Savoy',
                'description' => 'A legendary luxury hotel on the banks of the River Thames, offering timeless elegance and exceptional service.',
                'type' => 'hotel',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Strand, London WC2R 0EU, United Kingdom',
                'latitude' => 51.5111,
                'longitude' => -0.1206,
                'phone' => '+44 20 7836 4343',
                'email' => 'reservations@thesavoylondon.com',
                'website' => 'https://www.thesavoylondon.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'GBP',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Claridge\'s',
                'description' => 'An iconic Mayfair hotel known for its Art Deco elegance and impeccable service.',
                'type' => 'hotel',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Brook Street, London W1K 4HR, United Kingdom',
                'latitude' => 51.5154,
                'longitude' => -0.1447,
                'phone' => '+44 20 7629 8860',
                'email' => 'reservations@claridges.co.uk',
                'website' => 'https://www.claridges.co.uk',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'GBP',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'The Langham London',
                'description' => 'A grand Victorian hotel in the heart of London, offering luxury accommodations and world-class dining.',
                'type' => 'hotel',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => '1C Portland Place, Regent Street, London W1B 1JA, United Kingdom',
                'latitude' => 51.5186,
                'longitude' => -0.1431,
                'phone' => '+44 20 7636 1000',
                'email' => 'london@langhamhotels.com',
                'website' => 'https://london.langhamhotels.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'GBP',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],

            // New York Hotels
            [
                'name' => 'The Plaza',
                'description' => 'An iconic luxury hotel overlooking Central Park, known for its timeless elegance and exceptional service.',
                'type' => 'hotel',
                'destination_name' => 'New York',
                'country_code' => 'US',
                'address' => '768 5th Ave, New York, NY 10019, USA',
                'latitude' => 40.7648,
                'longitude' => -73.9748,
                'phone' => '+1 212-759-3000',
                'email' => 'reservations@theplaza.com',
                'website' => 'https://www.theplaza.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'USD',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'The St. Regis New York',
                'description' => 'A legendary luxury hotel on Fifth Avenue, offering refined accommodations and impeccable service.',
                'type' => 'hotel',
                'destination_name' => 'New York',
                'country_code' => 'US',
                'address' => '2 E 55th St, New York, NY 10022, USA',
                'latitude' => 40.7614,
                'longitude' => -73.9776,
                'phone' => '+1 212-753-4500',
                'email' => 'reservations@stregisnewyork.com',
                'website' => 'https://www.stregisnewyork.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'USD',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'The Ritz-Carlton New York, Central Park',
                'description' => 'A luxury hotel offering stunning views of Central Park and world-class amenities.',
                'type' => 'hotel',
                'destination_name' => 'New York',
                'country_code' => 'US',
                'address' => '50 Central Park S, New York, NY 10019, USA',
                'latitude' => 40.7658,
                'longitude' => -73.9764,
                'phone' => '+1 212-308-9100',
                'email' => 'reservations@ritzcarlton.com',
                'website' => 'https://www.ritzcarlton.com/en/hotels/new-york/central-park',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'USD',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],

            // Tokyo Hotels
            [
                'name' => 'The Ritz-Carlton Tokyo',
                'description' => 'A luxury hotel in the heart of Tokyo, offering panoramic city views and exceptional service.',
                'type' => 'hotel',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '9-7-1 Akasaka, Minato-ku, Tokyo 107-6245, Japan',
                'latitude' => 35.6762,
                'longitude' => 139.7303,
                'phone' => '+81 3-3423-8000',
                'email' => 'reservations@ritzcarlton.com',
                'website' => 'https://www.ritzcarlton.com/en/hotels/japan/tokyo',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'JPY',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Aman Tokyo',
                'description' => 'A serene luxury hotel offering minimalist elegance and exceptional service in the heart of Tokyo.',
                'type' => 'hotel',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '1-5-6 Otemachi, Chiyoda-ku, Tokyo 100-0004, Japan',
                'latitude' => 35.6869,
                'longitude' => 139.7633,
                'phone' => '+81 3-5224-3333',
                'email' => 'reservations@aman.com',
                'website' => 'https://www.aman.com/resorts/aman-tokyo',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'JPY',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Dubai Hotels
            [
                'name' => 'Burj Al Arab',
                'description' => 'An iconic luxury hotel shaped like a sail, offering unparalleled luxury and service.',
                'type' => 'hotel',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Jumeirah Beach Road, Dubai, UAE',
                'latitude' => 25.1413,
                'longitude' => 55.1853,
                'phone' => '+971 4 301 7777',
                'email' => 'reservations@burj-al-arab.com',
                'website' => 'https://www.burj-al-arab.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'AED',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool', 'beach_access'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Atlantis The Palm',
                'description' => 'A luxury resort on the iconic Palm Jumeirah, featuring world-class amenities and entertainment.',
                'type' => 'hotel',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Crescent Road, The Palm Jumeirah, Dubai, UAE',
                'latitude' => 25.1309,
                'longitude' => 55.1153,
                'phone' => '+971 4 426 2000',
                'email' => 'reservations@atlantisthepalm.com',
                'website' => 'https://www.atlantisthepalm.com',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'AED',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool', 'aquarium', 'water_park'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Rome Hotels
            [
                'name' => 'Hotel de Russie',
                'description' => 'A luxury hotel near the Spanish Steps, offering elegant accommodations and a beautiful secret garden.',
                'type' => 'hotel',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Via del Babuino, 9, 00187 Roma RM, Italy',
                'latitude' => 41.9058,
                'longitude' => 12.4822,
                'phone' => '+39 06 328 881',
                'email' => 'reservations@hotelderussie.it',
                'website' => 'https://www.roccofortehotels.com/hotels-and-resorts/hotel-de-russie/',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'garden'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'The First Roma Arte',
                'description' => 'A contemporary luxury hotel in the heart of Rome, featuring modern art and exceptional service.',
                'type' => 'hotel',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Via del Viminal, 8, 00184 Roma RM, Italy',
                'latitude' => 41.9009,
                'longitude' => 12.4953,
                'phone' => '+39 06 420 201',
                'email' => 'reservations@thefirsthotels.com',
                'website' => 'https://www.thefirsthotels.com/roma-arte',
                'opening_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
                'admission_fee' => 0.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
            ],
        ];

        foreach ($hotelAttractions as $hotelData) {
            $country = Country::where('iso_code', $hotelData['country_code'])->first();
            $destination = Destination::where('name', $hotelData['destination_name'])->first();
            
            if ($country && $destination) {
                // Remove lookup fields before creating the attraction
                unset($hotelData['destination_name'], $hotelData['country_code']);
                
                Attraction::updateOrCreate(
                    [
                        'name' => $hotelData['name'],
                        'destination_id' => $destination->id,
                    ],
                    array_merge($hotelData, [
                        'country_id' => $country->id,
                        'destination_id' => $destination->id,
                    ])
                );
            }
        }
    }
}
