<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Destination;
use App\Models\Hotel;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hotels = [
            // Paris Hotels
            [
                'name' => 'The Ritz Paris',
                'description' => 'A legendary luxury hotel in the heart of Paris, offering opulent accommodations and world-class service.',
                'type' => 'luxury',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '15 Place Vendôme, 75001 Paris, France',
                'latitude' => 48.8676,
                'longitude' => 2.3304,
                'phone' => '+33 1 43 16 30 30',
                'website' => 'https://www.ritzparis.com',
                'email' => 'reservations@ritzparis.com',
                'star_rating' => 5,
                'total_rooms' => 142,
                'room_types' => ['deluxe_room', 'suite', 'premium_suite', 'imperial_suite'],
                'price_range_min' => 1200.00,
                'price_range_max' => 5000.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Hotel Plaza Athénée',
                'description' => 'An iconic luxury hotel on Avenue Montaigne, known for its elegant rooms and exceptional dining.',
                'type' => 'luxury',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '25 Avenue Montaigne, 75008 Paris, France',
                'latitude' => 48.8661,
                'longitude' => 2.3044,
                'phone' => '+33 1 53 67 66 65',
                'website' => 'https://www.dorchestercollection.com',
                'email' => 'reservations@plaza-athenee-paris.com',
                'star_rating' => 5,
                'total_rooms' => 154,
                'room_types' => ['deluxe_room', 'suite', 'premium_suite', 'presidential_suite'],
                'price_range_min' => 1000.00,
                'price_range_max' => 4000.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Hotel des Grands Boulevards',
                'description' => 'A boutique hotel in the vibrant Grands Boulevards district, offering modern comfort with Parisian charm.',
                'type' => 'boutique',
                'destination_name' => 'Paris',
                'country_code' => 'FR',
                'address' => '17 Boulevard Poissonnière, 75002 Paris, France',
                'latitude' => 48.8721,
                'longitude' => 2.3444,
                'phone' => '+33 1 85 73 25 25',
                'website' => 'https://www.hoteldesgrandsboulevards.com',
                'email' => 'contact@hoteldesgrandsboulevards.com',
                'star_rating' => 4,
                'total_rooms' => 50,
                'room_types' => ['standard_room', 'deluxe_room', 'suite'],
                'price_range_min' => 200.00,
                'price_range_max' => 500.00,
                'currency_code' => 'EUR',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Tokyo Hotels
            [
                'name' => 'The Ritz-Carlton Tokyo',
                'description' => 'A luxury hotel in Roppongi, offering stunning city views and exceptional service in the heart of Tokyo.',
                'type' => 'luxury',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '9-7-1 Akasaka, Minato-ku, Tokyo 107-6245, Japan',
                'latitude' => 35.6703,
                'longitude' => 139.7286,
                'phone' => '+81 3 3423 8000',
                'website' => 'https://www.ritzcarlton.com',
                'email' => 'tcrty.reservations@ritzcarlton.com',
                'star_rating' => 5,
                'total_rooms' => 248,
                'room_types' => ['deluxe_room', 'executive_suite', 'presidential_suite', 'ritz_carlton_suite'],
                'price_range_min' => 80000.00,
                'price_range_max' => 300000.00,
                'currency_code' => 'JPY',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Park Hyatt Tokyo',
                'description' => 'An iconic luxury hotel in Shinjuku, famous for its elegant design and panoramic city views.',
                'type' => 'luxury',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '3-7-1-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo 163-1055, Japan',
                'latitude' => 35.6852,
                'longitude' => 139.6906,
                'phone' => '+81 3 5322 1234',
                'website' => 'https://www.hyatt.com',
                'email' => 'tokyo.park@hyatt.com',
                'star_rating' => 5,
                'total_rooms' => 177,
                'room_types' => ['park_king', 'park_twin', 'park_suite', 'presidential_suite'],
                'price_range_min' => 70000.00,
                'price_range_max' => 250000.00,
                'currency_code' => 'JPY',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Shibuya Sky Hotel',
                'description' => 'A modern hotel in the heart of Shibuya, offering contemporary comfort and easy access to Tokyo\'s attractions.',
                'type' => 'business',
                'destination_name' => 'Tokyo',
                'country_code' => 'JP',
                'address' => '2-1-1 Shibuya, Shibuya-ku, Tokyo 150-0002, Japan',
                'latitude' => 35.6580,
                'longitude' => 139.7016,
                'phone' => '+81 3 5456 0123',
                'website' => 'https://www.shibuyaskyhotel.com',
                'email' => 'info@shibuyaskyhotel.com',
                'star_rating' => 4,
                'total_rooms' => 120,
                'room_types' => ['standard_room', 'deluxe_room', 'executive_room'],
                'price_range_min' => 15000.00,
                'price_range_max' => 40000.00,
                'currency_code' => 'JPY',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center', 'business_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // New York City Hotels
            [
                'name' => 'The Plaza Hotel',
                'description' => 'An iconic luxury hotel on Central Park South, epitomizing New York elegance and sophistication.',
                'type' => 'luxury',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => '768 5th Ave, New York, NY 10019, USA',
                'latitude' => 40.7648,
                'longitude' => -73.9748,
                'phone' => '+1 212-759-3000',
                'website' => 'https://www.theplazany.com',
                'email' => 'reservations@theplazany.com',
                'star_rating' => 5,
                'total_rooms' => 282,
                'room_types' => ['deluxe_room', 'suite', 'grand_suite', 'presidential_suite'],
                'price_range_min' => 800.00,
                'price_range_max' => 3000.00,
                'currency_code' => 'USD',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'The Standard High Line',
                'description' => 'A trendy hotel in the Meatpacking District, known for its modern design and vibrant atmosphere.',
                'type' => 'boutique',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => '848 Washington St, New York, NY 10014, USA',
                'latitude' => 40.7406,
                'longitude' => -74.0080,
                'phone' => '+1 212-645-4646',
                'website' => 'https://www.standardhotels.com',
                'email' => 'reservations@standardhotels.com',
                'star_rating' => 4,
                'total_rooms' => 338,
                'room_types' => ['standard_room', 'deluxe_room', 'suite', 'penthouse'],
                'price_range_min' => 300.00,
                'price_range_max' => 800.00,
                'currency_code' => 'USD',
                'amenities' => ['restaurant', 'bar', 'rooftop', 'concierge', 'wifi', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Pod Hotel Times Square',
                'description' => 'A modern, efficient hotel in Times Square, offering smart design and great value in the heart of Manhattan.',
                'type' => 'budget',
                'destination_name' => 'New York City',
                'country_code' => 'US',
                'address' => '400 W 42nd St, New York, NY 10036, USA',
                'latitude' => 40.7589,
                'longitude' => -73.9851,
                'phone' => '+1 212-355-0300',
                'website' => 'https://www.thepodhotel.com',
                'email' => 'info@thepodhotel.com',
                'star_rating' => 3,
                'total_rooms' => 348,
                'room_types' => ['pod_room', 'queen_room', 'bunk_room'],
                'price_range_min' => 150.00,
                'price_range_max' => 300.00,
                'currency_code' => 'USD',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // London Hotels
            [
                'name' => 'The Savoy',
                'description' => 'A legendary luxury hotel on the Strand, combining Edwardian elegance with modern sophistication.',
                'type' => 'luxury',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Strand, London WC2R 0EU, UK',
                'latitude' => 51.5108,
                'longitude' => -0.1208,
                'phone' => '+44 20 7836 4343',
                'website' => 'https://www.fairmont.com',
                'email' => 'savoy@fairmont.com',
                'star_rating' => 5,
                'total_rooms' => 267,
                'room_types' => ['deluxe_room', 'suite', 'river_suite', 'royal_suite'],
                'price_range_min' => 600.00,
                'price_range_max' => 2000.00,
                'currency_code' => 'GBP',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'The Ned',
                'description' => 'A stylish hotel in the City of London, housed in a former bank building with a vibrant social scene.',
                'type' => 'boutique',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => '27 Poultry, London EC2R 8AJ, UK',
                'latitude' => 51.5154,
                'longitude' => -0.0922,
                'phone' => '+44 20 3828 2000',
                'website' => 'https://www.thened.com',
                'email' => 'reservations@thened.com',
                'star_rating' => 5,
                'total_rooms' => 250,
                'room_types' => ['cosy_room', 'medium_room', 'large_room', 'suite'],
                'price_range_min' => 300.00,
                'price_range_max' => 800.00,
                'currency_code' => 'GBP',
                'amenities' => ['restaurant', 'bar', 'spa', 'concierge', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Premier Inn London County Hall',
                'description' => 'A comfortable budget hotel near the London Eye, offering great value and excellent location.',
                'type' => 'budget',
                'destination_name' => 'London',
                'country_code' => 'GB',
                'address' => 'Belvedere Rd, London SE1 7PB, UK',
                'latitude' => 51.5045,
                'longitude' => -0.1195,
                'phone' => '+44 871 527 8648',
                'website' => 'https://www.premierinn.com',
                'email' => 'customer.services@premierinn.com',
                'star_rating' => 3,
                'total_rooms' => 313,
                'room_types' => ['standard_room', 'family_room'],
                'price_range_min' => 80.00,
                'price_range_max' => 200.00,
                'currency_code' => 'GBP',
                'amenities' => ['restaurant', 'bar', 'wifi', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Rome Hotels
            [
                'name' => 'Hotel de Russie',
                'description' => 'A luxury hotel near the Spanish Steps, offering elegant accommodations and a beautiful secret garden.',
                'type' => 'luxury',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Via del Babuino, 9, 00187 Roma RM, Italy',
                'latitude' => 41.9064,
                'longitude' => 12.4818,
                'phone' => '+39 06 328 881',
                'website' => 'https://www.roccofortehotels.com',
                'email' => 'derussie@roccofortehotels.com',
                'star_rating' => 5,
                'total_rooms' => 122,
                'room_types' => ['deluxe_room', 'suite', 'garden_suite', 'presidential_suite'],
                'price_range_min' => 500.00,
                'price_range_max' => 1500.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'The First Roma Arte',
                'description' => 'A contemporary art hotel near Termini Station, featuring modern design and excellent connectivity.',
                'type' => 'boutique',
                'destination_name' => 'Rome',
                'country_code' => 'IT',
                'address' => 'Via del Viminal, 8, 00184 Roma RM, Italy',
                'latitude' => 41.9019,
                'longitude' => 12.4953,
                'phone' => '+39 06 420 201',
                'website' => 'https://www.thefirsthotels.com',
                'email' => 'info@thefirsthotels.com',
                'star_rating' => 4,
                'total_rooms' => 88,
                'room_types' => ['standard_room', 'deluxe_room', 'suite'],
                'price_range_min' => 200.00,
                'price_range_max' => 500.00,
                'currency_code' => 'EUR',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center', 'business_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Sydney Hotels
            [
                'name' => 'Park Hyatt Sydney',
                'description' => 'A luxury hotel with stunning harbor views, located between the Sydney Opera House and Harbour Bridge.',
                'type' => 'luxury',
                'destination_name' => 'Sydney',
                'country_code' => 'AU',
                'address' => '7 Hickson Rd, The Rocks NSW 2000, Australia',
                'latitude' => -33.8572,
                'longitude' => 151.2099,
                'phone' => '+61 2 9256 1234',
                'website' => 'https://www.hyatt.com',
                'email' => 'sydney.park@hyatt.com',
                'star_rating' => 5,
                'total_rooms' => 155,
                'room_types' => ['harbour_room', 'harbour_suite', 'opera_suite', 'presidential_suite'],
                'price_range_min' => 800.00,
                'price_range_max' => 2500.00,
                'currency_code' => 'AUD',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'QT Sydney',
                'description' => 'A quirky boutique hotel in the heart of Sydney, known for its unique design and vibrant atmosphere.',
                'type' => 'boutique',
                'destination_name' => 'Sydney',
                'country_code' => 'AU',
                'address' => '49 Market St, Sydney NSW 2000, Australia',
                'latitude' => -33.8705,
                'longitude' => 151.2071,
                'phone' => '+61 2 8262 0000',
                'website' => 'https://www.qthotels.com',
                'email' => 'sydney@qthotels.com',
                'star_rating' => 4,
                'total_rooms' => 200,
                'room_types' => ['standard_room', 'deluxe_room', 'suite', 'penthouse'],
                'price_range_min' => 300.00,
                'price_range_max' => 800.00,
                'currency_code' => 'AUD',
                'amenities' => ['restaurant', 'bar', 'spa', 'concierge', 'wifi', 'fitness_center'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Dubai Hotels
            [
                'name' => 'Burj Al Arab',
                'description' => 'The world\'s most luxurious hotel, shaped like a sail and standing on its own artificial island.',
                'type' => 'luxury',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Jumeirah St, Dubai, UAE',
                'latitude' => 25.1413,
                'longitude' => 55.1853,
                'phone' => '+971 4 301 7777',
                'website' => 'https://www.jumeirah.com',
                'email' => 'baa@jumeirah.com',
                'star_rating' => 5,
                'total_rooms' => 202,
                'room_types' => ['deluxe_suite', 'club_suite', 'presidential_suite', 'royal_suite'],
                'price_range_min' => 2000.00,
                'price_range_max' => 8000.00,
                'currency_code' => 'AED',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'pool', 'beach_access'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Atlantis The Palm',
                'description' => 'A luxury resort on Palm Jumeirah, featuring an underwater suite and world-class entertainment.',
                'type' => 'resort',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Crescent Rd, Dubai, UAE',
                'latitude' => 25.1309,
                'longitude' => 55.1153,
                'phone' => '+971 4 426 0000',
                'website' => 'https://www.atlantisthepalm.com',
                'email' => 'reservations@atlantisthepalm.com',
                'star_rating' => 5,
                'total_rooms' => 1539,
                'room_types' => ['deluxe_room', 'suite', 'underwater_suite', 'royal_suite'],
                'price_range_min' => 800.00,
                'price_range_max' => 3000.00,
                'currency_code' => 'AED',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'pool', 'aquarium', 'water_park'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Rove Downtown',
                'description' => 'A modern lifestyle hotel in Downtown Dubai, offering contemporary comfort with great value.',
                'type' => 'lifestyle',
                'destination_name' => 'Dubai',
                'country_code' => 'AE',
                'address' => 'Sheikh Mohammed bin Rashid Blvd, Dubai, UAE',
                'latitude' => 25.1972,
                'longitude' => 55.2796,
                'phone' => '+971 4 561 9000',
                'website' => 'https://www.rovehotels.com',
                'email' => 'downtown@rovehotels.com',
                'star_rating' => 4,
                'total_rooms' => 420,
                'room_types' => ['rove_room', 'rove_plus_room', 'family_room'],
                'price_range_min' => 300.00,
                'price_range_max' => 600.00,
                'currency_code' => 'AED',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Barcelona Hotels
            [
                'name' => 'Hotel Casa Fuster',
                'description' => 'A luxury hotel in a modernist building on Passeig de Gràcia, offering elegant accommodations and rooftop views.',
                'type' => 'luxury',
                'destination_name' => 'Barcelona',
                'country_code' => 'ES',
                'address' => 'Passeig de Gràcia, 132, 08008 Barcelona, Spain',
                'latitude' => 41.3954,
                'longitude' => 2.1611,
                'phone' => '+34 932 55 30 00',
                'website' => 'https://www.hotelcasafuster.com',
                'email' => 'info@hotelcasafuster.com',
                'star_rating' => 5,
                'total_rooms' => 105,
                'room_types' => ['deluxe_room', 'suite', 'premium_suite', 'presidential_suite'],
                'price_range_min' => 400.00,
                'price_range_max' => 1200.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'rooftop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Hotel Omm',
                'description' => 'A contemporary design hotel in the Eixample district, known for its modern architecture and vibrant atmosphere.',
                'type' => 'boutique',
                'destination_name' => 'Barcelona',
                'country_code' => 'ES',
                'address' => 'Carrer del Rosselló, 265, 08008 Barcelona, Spain',
                'latitude' => 41.3954,
                'longitude' => 2.1611,
                'phone' => '+34 934 45 40 00',
                'website' => 'https://www.hotelomm.es',
                'email' => 'info@hotelomm.es',
                'star_rating' => 5,
                'total_rooms' => 91,
                'room_types' => ['standard_room', 'deluxe_room', 'suite', 'penthouse'],
                'price_range_min' => 250.00,
                'price_range_max' => 600.00,
                'currency_code' => 'EUR',
                'amenities' => ['restaurant', 'bar', 'spa', 'concierge', 'wifi', 'fitness_center', 'rooftop'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],

            // Bangkok Hotels
            [
                'name' => 'The Siam',
                'description' => 'A luxury riverside hotel in Bangkok, offering traditional Thai elegance with modern amenities.',
                'type' => 'luxury',
                'destination_name' => 'Bangkok',
                'country_code' => 'TH',
                'address' => '3/2 Thanon Khao, Vachirapayabal, Dusit, Bangkok 10300, Thailand',
                'latitude' => 13.7783,
                'longitude' => 100.5101,
                'phone' => '+66 2 206 6999',
                'website' => 'https://www.thesiamhotel.com',
                'email' => 'reservations@thesiamhotel.com',
                'star_rating' => 5,
                'total_rooms' => 39,
                'room_types' => ['deluxe_room', 'suite', 'villa', 'presidential_suite'],
                'price_range_min' => 15000.00,
                'price_range_max' => 50000.00,
                'currency_code' => 'THB',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Siam Kempinski Hotel Bangkok',
                'description' => 'A luxury hotel in the heart of Bangkok, featuring lush gardens and world-class service.',
                'type' => 'luxury',
                'destination_name' => 'Bangkok',
                'country_code' => 'TH',
                'address' => '991/9 Rama I Rd, Pathum Wan, Bangkok 10330, Thailand',
                'latitude' => 13.7462,
                'longitude' => 100.5347,
                'phone' => '+66 2 162 9000',
                'website' => 'https://www.kempinski.com',
                'email' => 'bangkok@kempinski.com',
                'star_rating' => 5,
                'total_rooms' => 397,
                'room_types' => ['deluxe_room', 'suite', 'presidential_suite', 'royal_suite'],
                'price_range_min' => 8000.00,
                'price_range_max' => 25000.00,
                'currency_code' => 'THB',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'valet_parking', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Ariyasom Villa',
                'description' => 'A boutique hotel in a traditional Thai house, offering authentic charm and personalized service.',
                'type' => 'boutique',
                'destination_name' => 'Bangkok',
                'country_code' => 'TH',
                'address' => '65 Sukhumvit Soi 1, Khlong Toei Nuea, Watthana, Bangkok 10110, Thailand',
                'latitude' => 13.7442,
                'longitude' => 100.5528,
                'phone' => '+66 2 254 8880',
                'website' => 'https://www.ariyasom.com',
                'email' => 'info@ariyasom.com',
                'star_rating' => 4,
                'total_rooms' => 24,
                'room_types' => ['deluxe_room', 'suite', 'villa'],
                'price_range_min' => 3000.00,
                'price_range_max' => 8000.00,
                'currency_code' => 'THB',
                'amenities' => ['restaurant', 'spa', 'concierge', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],

            // Santorini Hotels
            [
                'name' => 'Grace Hotel Santorini',
                'description' => 'A luxury hotel in Imerovigli with stunning caldera views, offering intimate luxury and exceptional service.',
                'type' => 'luxury',
                'destination_name' => 'Santorini',
                'country_code' => 'GR',
                'address' => 'Imerovigli, Santorini 847 00, Greece',
                'latitude' => 36.4306,
                'longitude' => 25.4219,
                'phone' => '+30 2286 021300',
                'website' => 'https://www.gracehotels.com',
                'email' => 'santorini@gracehotels.com',
                'star_rating' => 5,
                'total_rooms' => 20,
                'room_types' => ['deluxe_room', 'suite', 'honeymoon_suite', 'presidential_suite'],
                'price_range_min' => 600.00,
                'price_range_max' => 2000.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Katikies Hotel',
                'description' => 'A luxury hotel in Oia with breathtaking sunset views, featuring traditional Cycladic architecture.',
                'type' => 'luxury',
                'destination_name' => 'Santorini',
                'country_code' => 'GR',
                'address' => 'Oia, Santorini 847 02, Greece',
                'latitude' => 36.4619,
                'longitude' => 25.3753,
                'phone' => '+30 2286 071801',
                'website' => 'https://www.katikies.com',
                'email' => 'info@katikies.com',
                'star_rating' => 5,
                'total_rooms' => 25,
                'room_types' => ['deluxe_room', 'suite', 'honeymoon_suite', 'presidential_suite'],
                'price_range_min' => 500.00,
                'price_range_max' => 1500.00,
                'currency_code' => 'EUR',
                'amenities' => ['spa', 'restaurant', 'bar', 'concierge', 'room_service', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Astra Suites',
                'description' => 'A boutique hotel in Imerovigli, offering traditional charm with modern comfort and spectacular views.',
                'type' => 'boutique',
                'destination_name' => 'Santorini',
                'country_code' => 'GR',
                'address' => 'Imerovigli, Santorini 847 00, Greece',
                'latitude' => 36.4306,
                'longitude' => 25.4219,
                'phone' => '+30 2286 023641',
                'website' => 'https://www.astrasuites.com',
                'email' => 'info@astrasuites.com',
                'star_rating' => 4,
                'total_rooms' => 12,
                'room_types' => ['standard_suite', 'deluxe_suite', 'honeymoon_suite'],
                'price_range_min' => 300.00,
                'price_range_max' => 800.00,
                'currency_code' => 'EUR',
                'amenities' => ['restaurant', 'bar', 'concierge', 'wifi', 'fitness_center', 'pool'],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
        ];

        foreach ($hotels as $hotelData) {
            $country = Country::where('iso_code', $hotelData['country_code'])->first();
            $destination = Destination::where('name', $hotelData['destination_name'])->first();
            
            if ($country && $destination) {
                // Remove lookup fields that are not actual table columns
                $insertData = $hotelData;
                unset($insertData['destination_name'], $insertData['country_code']);
                
                Hotel::updateOrCreate(
                    [
                        'name' => $hotelData['name'],
                        'destination_id' => $destination->id,
                    ],
                    array_merge($insertData, [
                        'country_id' => $country->id,
                        'destination_id' => $destination->id,
                    ])
                );
            }
        }
    }
}